import type { Metadata } from 'next'
import React from 'react'
import { ThemeProvider } from 'next-themes'
import { robotoMono } from '~/styles/fonts'
import '~/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='vi' suppressHydrationWarning>
      <body className={`${robotoMono.variable} font-roboto-mono antialiased`} suppressHydrationWarning>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
