services:
  postgres:
    restart: always
    env_file:
      - ../backend/.env.development
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    name: app-network
    driver: bridge
